<?php

return
    [
        'folder'=>get_template_directory_uri().'/public',
        'data'=>
            [
                [
                    'src'=>'/js/index.js',
                    'deps'=>null,
                    'ver'=>null,
                    'in_footer'=>false,
                ],
                [
                    'src'=>'/css/bootstrap.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                ],
                [
                    'src'=>'/css/style.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                ],
                /*
                 * Catalog
                 */
                [
                    'src'=>'/css/catalog-grid.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                    'condition'=>true===_is_shop() or true===is_tax('product_cat'),
                ],
                [
                    'src'=>'/js/catalog-grid.js',
                    'deps'=>null,
                    'ver'=>null,
                    'in_footer'=>true,
                    'condition'=>_is_shop() or is_tax('product_cat'),
                ],
                /*
                 * Product
                 */
                [
                    'src'=>'/css/product.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                    'condition'=>is_product(),
                ],
                [
                    'src'=>'/js/product.js',
                    'deps'=>null,
                    'ver'=>null,
                    'in_footer'=>true,
                    'condition'=>is_product(),
                ],
                [
                    'src'=>'/css/similar-products.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                    'condition'=>is_product(),
                ],
                [
                    'src'=>'/js/similar-products.js',
                    'deps'=>null,
                    'ver'=>null,
                    'in_footer'=>true,
                    'condition'=>is_product(),
                ],
                [
                    'src'=>'/css/related-products.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                    'condition'=>is_product(),
                ],
                [
                    'src'=>'/js/related-products.js',
                    'deps'=>null,
                    'ver'=>null,
                    'in_footer'=>true,
                    'condition'=>is_product(),
                ],
                [
                    'src'=>'/css/feedback_description.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                    'condition'=>is_product(),
                ],
                [
                    'src'=>'/js/feedback_description.js',
                    'deps'=>null,
                    'ver'=>null,
                    'in_footer'=>true,
                    'condition'=>is_product(),
                ],
                /*
                 * Basket
                 */
                [
                    'src'=>'/css/basket.css',
                    'deps'=>null,
                    'ver'=>null,
                    'media'=>false,//https://www.w3.org/TR/CSS2/media.html#media-types
                    'condition'=>is_cart() ,
                ],
                [
                    'src'=>'/js/basket.js',
                    'deps'=>null,
                    'ver'=>null,
                    'in_footer'=>true,
                    'condition'=>is_cart() ,
                ],
            ],
    ];
